version: '3.8'

services:
  calculator:
    image: calculator:latest
    ports:
      - '3000:3000' # Ánh xạ cổng 3000 của host với cổng 3000 của container
    environment:
      - NODE_ENV=production # Thiết lập biến môi trường cho môi trường production
    restart: unless-stopped # Tự động restart container trừ khi bạn dừng thủ công
